package com.myspace.workshop;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Persona implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Ine")
	private java.lang.String INE;
	@org.kie.api.definition.type.Label(value = "Nombre")
	private java.lang.String nombre;
	@org.kie.api.definition.type.Label(value = "Apellido")
	private java.lang.String apellido;
	@org.kie.api.definition.type.Label(value = "Fecha de nacimiento")
	private java.time.LocalDate fxNacimiento;
	@org.kie.api.definition.type.Label(value = "Comentarios")
	private java.util.List<java.lang.String> comments;

	public Persona() {
	}

	public java.lang.String getINE() {
		return this.INE;
	}

	public void setINE(java.lang.String INE) {
		this.INE = INE;
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.String getApellido() {
		return this.apellido;
	}

	public void setApellido(java.lang.String apellido) {
		this.apellido = apellido;
	}

	public java.time.LocalDate getFxNacimiento() {
		return this.fxNacimiento;
	}

	public void setFxNacimiento(java.time.LocalDate fxNacimiento) {
		this.fxNacimiento = fxNacimiento;
	}

	public java.util.List<java.lang.String> getComments() {
		return this.comments;
	}

	public void setComments(java.util.List<java.lang.String> comments) {
		this.comments = comments;
	}

	public Persona(java.lang.String INE, java.lang.String nombre,
			java.lang.String apellido, java.time.LocalDate fxNacimiento,
			java.util.List<java.lang.String> comments) {
		this.INE = INE;
		this.nombre = nombre;
		this.apellido = apellido;
		this.fxNacimiento = fxNacimiento;
		this.comments = comments;
	}

}